# This is a basic workflow to help you get started with Actions

name: Upgrade AKS Cluster

# Controls when the action will run. 
on:
    schedule: 
      - cron: '0 3 */15 * *'
        
jobs:
  upgrade-node:
        name: Upgrading Node images
        runs-on: ubuntu-latest
